services:
  - type: web
    name: jay-discord-proxy
    runtime: node
    plan: free
    region: singapore
    branch: proxy
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: /health
    autoDeploy: true
