use_default_settings: true

general:
  instance_name: "Jay Eyes"
  contact_url: false
  enable_metrics: false
  donation_url: false

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: "vi"
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey"
  limiter: false
  public_instance: false
  image_proxy: false
  http_protocol_version: "1.0"
  method: "GET"

ui:
  static_use_hash: true
  default_locale: "en"
  query_in_title: false
  infinite_scroll: false

outgoing:
  request_timeout: 8.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20
  enable_http2: true

engines:
  - name: google
    disabled: false
    weight: 2
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
    weight: 2
  - name: brave
    disabled: false
  - name: qwant
    disabled: false
  - name: startpage
    disabled: false
  - name: mojeek
    disabled: false
  - name: wikipedia
    disabled: false
  - name: yahoo
    disabled: false
  - name: google news
    disabled: false
  - name: bing news
    disabled: false
  - name: duckduckgo news
    disabled: false
